/**
 * ChatMessage component - renders a single message in the conversation.
 *
 * Handles both user and agent messages with different styling.
 * Displays citations, timestamps, agent badges, and verification status.
 * Per TEIS disclosure requirements: all agent messages include AI disclosure.
 */

import { format } from 'date-fns'
import { Bot, User as UserIcon, ShieldCheck, AlertTriangle } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import type { Message } from '@/types'

interface ChatMessageProps {
  message: Message
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isAgent = message.role === 'agent'
  const timestamp = format(new Date(message.created_at), 'h:mm a')

  return (
    <div
      className={cn(
        'flex gap-3 mb-4',
        isAgent ? 'justify-start' : 'justify-end'
      )}
    >
      {isAgent && (
        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
          <Bot className="w-5 h-5 text-primary" />
        </div>
      )}

      <div className={cn('flex flex-col gap-2 max-w-[70%]', !isAgent && 'items-end')}>
        {/* Message header */}
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          {isAgent && message.agent_name && (
            <Badge variant="secondary" className="font-normal">
              {message.agent_name}
            </Badge>
          )}
          <span>{timestamp}</span>
          {message.verification_status === 'verified' && (
            <ShieldCheck className="w-3 h-3 text-green-500" />
          )}
          {message.verification_status === 'flagged' && (
            <AlertTriangle className="w-3 h-3 text-yellow-500" />
          )}
        </div>

        {/* Message content */}
        <Card
          className={cn(
            'p-4',
            isAgent
              ? 'bg-card border-border'
              : 'bg-primary text-primary-foreground border-primary'
          )}
        >
          {/* Content with markdown rendering (sanitized) */}
          <div
            className="prose prose-sm dark:prose-invert max-w-none"
            dangerouslySetInnerHTML={{ __html: sanitizeHtml(message.content) }}
          />

          {/* Citations */}
          {message.citations.length > 0 && (
            <div className="mt-3 pt-3 border-t border-border/50">
              <div className="text-xs text-muted-foreground mb-2">Sources:</div>
              <div className="flex flex-wrap gap-2">
                {message.citations.map((citation) => (
                  <Badge
                    key={citation.index}
                    variant="outline"
                    className="text-xs cursor-pointer hover:bg-accent"
                    title={citation.content_snippet}
                  >
                    [{citation.index}] {citation.document_name}
                    {citation.page_number && ` p.${citation.page_number}`}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          {/* AI Disclosure (required by TEIS for all agent messages) */}
          {isAgent && (
            <div className="mt-3 pt-3 border-t border-border/50 text-xs text-muted-foreground italic">
              This response was generated by AI. Verify critical information with official sources.
            </div>
          )}
        </Card>
      </div>

      {!isAgent && (
        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-secondary flex items-center justify-center">
          <UserIcon className="w-5 h-5 text-secondary-foreground" />
        </div>
      )}
    </div>
  )
}

/**
 * Basic HTML sanitization for markdown content.
 * In production, use DOMPurify or a similar library.
 * This is a simplified version for demonstration.
 */
function sanitizeHtml(html: string): string {
  // Basic newline to <br> conversion for plain text
  // In production: use marked + DOMPurify for proper markdown rendering
  return html
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>')
}
