"""Analytics models for tracking usage metrics and daily summaries.

Design principles:
- UsageMetric: Raw metric events (API calls, token usage, agent runs, etc.)
- DailySummary: Pre-aggregated daily rollups for fast dashboard queries
- All queries scoped by tenant_id for multi-tenancy
- Proper indexes for time-range queries
- JSONB dimensions for flexible metric attributes
"""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database import Base


class MetricType(StrEnum):
    """Types of metrics tracked by the analytics system."""

    API_CALL = "api_call"
    TOKEN_USAGE = "token_usage"
    AGENT_RUN = "agent_run"
    TOOL_CALL = "tool_call"
    DOCUMENT_QUERY = "document_query"


class UsageMetric(Base):
    """Raw usage metric event.

    Each record represents a single event (API call, token usage, etc.)
    with flexible dimensions stored in JSONB for metric-specific attributes.
    """

    __tablename__ = "usage_metrics"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    metric_type: Mapped[MetricType] = mapped_column(
        Enum(MetricType, name="metric_type"),
        nullable=False,
        index=True,
    )

    # Numeric value for the metric (1.0 for counts, token count, duration, etc.)
    value: Mapped[float] = mapped_column(Float, nullable=False)

    # Flexible dimensions based on metric type:
    # - API_CALL: {endpoint, method, status_code, response_time_ms, user_id}
    # - TOKEN_USAGE: {model, prompt_tokens, completion_tokens, cost}
    # - AGENT_RUN: {agent_id, duration_ms, steps, status, user_id}
    # - TOOL_CALL: {tool_name, duration_ms, success}
    # - DOCUMENT_QUERY: {query_type, result_count, duration_ms}
    dimensions: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default="{}",
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        default=lambda: datetime.now(UTC),
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
    )

    # Relationships
    tenant: Mapped[Tenant] = relationship("Tenant")  # type: ignore[name-defined]

    __table_args__ = (
        # Composite indexes for common query patterns
        Index("ix_usage_metrics_tenant_timestamp", "tenant_id", "timestamp"),
        Index("ix_usage_metrics_tenant_type", "tenant_id", "metric_type"),
        Index("ix_usage_metrics_tenant_type_timestamp", "tenant_id", "metric_type", "timestamp"),
    )

    def __repr__(self) -> str:
        return f"<UsageMetric id={self.id} type={self.metric_type} tenant={self.tenant_id}>"


class DailySummary(Base):
    """Pre-aggregated daily summary for fast dashboard queries.

    Generated by the analytics service, typically via a scheduled job
    that runs daily to aggregate the previous day's metrics.
    """

    __tablename__ = "daily_summaries"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    date: Mapped[date] = mapped_column(Date, nullable=False, index=True)

    # Aggregated metrics
    total_api_calls: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_agent_runs: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    unique_users: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    avg_response_time_ms: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    error_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_estimate: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Additional structured data (top models used, peak hours, etc.)
    dimensions: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default="{}",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
    )

    # Relationships
    tenant: Mapped[Tenant] = relationship("Tenant")  # type: ignore[name-defined]

    __table_args__ = (
        # Unique constraint: one summary per tenant per day
        Index("ix_daily_summaries_tenant_date", "tenant_id", "date", unique=True),
    )

    def __repr__(self) -> str:
        return f"<DailySummary tenant={self.tenant_id} date={self.date}>"
